monolog:
    channels: [ "app" ]

    handlers:
        # Main log handler
        main:
            type: stream
            level: debug
            channels: [ "app" ]
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            # Vous pouvez supprimer 'use_microseconds' car il n'est pas valide.

        # Error log handler (optionnel)
        error:
            type: stream
            level: error
            path: "%kernel.logs_dir%/error.log"

        # Example of sending logs to a remote server
        # remote:
        #     type: fingers_crossed
        #     action_level: error
        #     handler: group
