security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: database_users

            form_login:
                login_path: connexion
                check_path: connexion
                # Route après une connexion réussie
                default_target_path: mon_espace
                # Si vous voulez récupérer une route d'erreur, définissez cette option
                failure_path: connexion

            logout:
                path: logout
                target: connexion

            switch_user: true

    access_control:
        - { path: ^/mon-espace, roles: ROLE_USER }
