controllers:
  resource: ../src/Controller/
  type: annotation

about:
  path: /about
  controller: App\Controller\SecurityController::about

inscription:
  path: /inscription
  controller: App\Controller\RegistrationController::inscription

connexion:
  path: /connexion
  controller: App\Controller\SecurityController::connexion

list:
  path: /events
  controller: App\Controller\EventController::list
